on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.REPOSITORY_CONFIG_TESTER_APP_ID }}
          private-key: ${{ secrets.REPOSITORY_CONFIG_TESTER_PRIVATE_KEY }}
      - run: vitest run
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.github_token }}
